### ISSUE TITLE
ImportError: No module named ansible.constants

### ISSUE THREAD

**Issue by vladdancer** [ahes/ansible-filter-plugins#2]
When I try to run a command `python filter_plugins/vault.py --salt` I get an error:
```
Traceback (most recent call last):
  File "filter_plugins/vault.py", line 55, in <module>
    import ansible.constants as C
ImportError: No module named ansible.constants
```
Do you have any suggestions how to fix this?

ansible --version
```
ansible 2.1.0
  config file = /Users/demo/projects/test/cnf/env/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by ahes** [comment]
Try to load Ansible environment, i.e. clone ansible repo from github and run:
`source hacking/env-setup`. 

Basically this is how I run ansible.

Other way would be to set env variable pointing ansible libraries, i.e.: 
`export PYTHONPATH=/tmp/ansible/lib`

where `/tmp/ansible` is ansible sources.

**Comment by asangal** [comment]
Where is this hacking/env-setup file if I downloaded/using ansible using it as a .tar.gz downloaded artifact.

**Comment by zsustar** [comment]
put a colon after the export PYTHONPATH=/tmp/ansible/lib
like following
export PYTHONPATH=/tmp/ansible/lib:

**Comment by jeremykohn** [comment]
@asangal Unzip the .tar.gz, or git clone the ansible repo, and then cd into the 'ansible' folder before you run hacking/env-setup.

The file is: https://github.com/ansible/ansible/blob/devel/hacking/env-setup
